//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyMM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int PurchaseDetailID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
